#!/usr/bin/env python3
"""Verify that our MySQL/TRES-based pipeline produces the same values as sacct.

Compares per-job metrics between:
  - sacct CSV:  dev_scripts/sacct_jobs_2weeks_july.csv
                (produced by: sacct -nPo JobID,User,State,Elapsed,TotalCPU,MaxRSS,
                 AllocCPUs,ReqMem --starttime=2025-07-01 --endtime=2025-07-15
                 --allusers | tr '|' ',' >> sacct_jobs_2weeks_july.csv)
  - DB CSV:     results/2025-07-01_2025-12-31_job_level_metrics.csv
                (produced by our slurm_utils.py pipeline from MySQL)

Fields compared:
  - Elapsed time (seconds)
  - TotalCPU time (seconds)
  - AllocCPUs
  - ReqMem (total requested memory in bytes)
  - MaxRSS (peak memory usage in bytes)

Saves output to dev_scripts/output_verify_sacct_mysql_compatibility.txt
"""

import csv
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
# sacct side: a MANUAL export you must produce first (see the sacct command in the
# module docstring above); drop it here in dev_scripts/. Not generated by any script.
SACCT_FILE = SCRIPT_DIR / "sacct_jobs_2weeks_july.csv"
# DB side: produced by the slurm_utils.py pipeline, which writes under results/data/.
DB_FILE = PROJECT_ROOT / "results" / "data" / "2025-07-01_2025-12-31_job_level_metrics.csv"
OUTPUT_DIR = SCRIPT_DIR / "output"
OUTPUT_DIR.mkdir(exist_ok=True)
OUTPUT_FILE = OUTPUT_DIR / "output_verify_sacct_mysql_compatibility.txt"
def out(text=""):
    print(text)
    print(text, file=outf)


# ---------------------------------------------------------------------------
# Parsers for sacct fields
# ---------------------------------------------------------------------------

def parse_elapsed(s):
    """Parse sacct elapsed 'D-HH:MM:SS' or 'HH:MM:SS' to seconds."""
    days = 0
    if '-' in s:
        d, s = s.split('-', 1)
        days = int(d)
    parts = s.split(':')
    if len(parts) == 3:
        h, m, sec = parts
        return days * 86400 + int(h) * 3600 + int(m) * 60 + float(sec)
    return 0


def parse_totalcpu(s):
    """Parse sacct TotalCPU to seconds (D-HH:MM:SS or HH:MM:SS.mmm or MM:SS.mmm)."""
    if not s:
        return 0
    days = 0
    if '-' in s:
        d, s = s.split('-', 1)
        days = int(d)
    parts = s.split(':')
    if len(parts) == 3:
        h, m, sec = parts
        return days * 86400 + int(h) * 3600 + int(m) * 60 + float(sec)
    elif len(parts) == 2:
        m, sec = parts
        return days * 86400 + int(m) * 60 + float(sec)
    return 0


def parse_mem_value(s):
    """Parse sacct memory string like '8000M', '3600G', '1024K' to bytes.
    Strips optional trailing 'c' (per-cpu) or 'n' (per-node) suffix."""
    if not s or ':' in s:
        return 0
    s = s.strip()
    if s and s[-1] in ('c', 'n'):
        s = s[:-1]
    if s.endswith('G'):
        return float(s[:-1]) * 1024**3
    elif s.endswith('M'):
        return float(s[:-1]) * 1024**2
    elif s.endswith('K'):
        return float(s[:-1]) * 1024
    elif s.endswith('T'):
        return float(s[:-1]) * 1024**4
    try:
        return float(s)
    except ValueError:
        return 0


# ---------------------------------------------------------------------------
# Load DB CSV
# ---------------------------------------------------------------------------

db = {}
with open(DB_FILE) as f:
    f.readline()  # skip '# date_range:' comment
    reader = csv.DictReader(f)
    for row in reader:
        db[row['job_id']] = row

# ---------------------------------------------------------------------------
# Load sacct CSV and match
# ---------------------------------------------------------------------------

# sacct columns (no header): JobID, User, State, Elapsed, TotalCPU, MaxRSS,
#                             AllocCPUs, ReqMem

# For MaxRSS we need to look at step-level rows (*.batch, *.N) because
# sacct only reports MaxRSS at the step level.
job_sacct_maxrss = {}  # job_id -> (maxrss_bytes, step_id, raw_string)

job_rows = []  # (sacct_row, db_row) for pure job-level entries

with open(SACCT_FILE) as f:
    reader = csv.reader(f)
    for row in reader:
        if len(row) < 8:
            continue
        jobid_full = row[0]

        # Collect step-level MaxRSS
        base_match = re.match(r'^(\d+)', jobid_full)
        if base_match:
            base_id = base_match.group(1)
            maxrss = parse_mem_value(row[5])
            if maxrss > 0:
                if base_id not in job_sacct_maxrss or maxrss > job_sacct_maxrss[base_id][0]:
                    job_sacct_maxrss[base_id] = (maxrss, jobid_full, row[5])

        # Pure job-level rows (no dots, no underscores) for other comparisons
        if re.match(r'^\d+$', jobid_full) and row[2] == 'COMPLETED' and jobid_full in db:
            job_rows.append((row, db[jobid_full]))


# ---------------------------------------------------------------------------
# Compare
# ---------------------------------------------------------------------------

with open(OUTPUT_FILE, 'w') as outf:

    out("=" * 80)
    out("VERIFICATION: sacct vs MySQL pipeline")
    out("=" * 80)
    out()
    out(f"sacct file:  {SACCT_FILE.name}")
    out(f"DB file:     {DB_FILE.name}")
    out(f"Matched COMPLETED jobs: {len(job_rows)}")
    out()

    # -----------------------------------------------------------------------
    # Part 1: Elapsed time
    # -----------------------------------------------------------------------
    out("=" * 80)
    out("PART 1: Elapsed time (seconds)")
    out("=" * 80)
    out()

    el_match = el_diff = 0
    el_samples = []
    for sacct_row, db_row in job_rows:
        s_val = parse_elapsed(sacct_row[3])
        d_val = float(db_row['elapsed_sec']) if db_row['elapsed_sec'] else 0
        if abs(s_val - d_val) < 2:
            el_match += 1
        else:
            el_diff += 1
            if len(el_samples) < 5:
                el_samples.append((sacct_row[0], sacct_row[3], s_val, d_val))

    total = el_match + el_diff
    out(f"  Match (±1 sec):  {el_match:>8} ({el_match/total*100:.2f}%)")
    out(f"  Differ:          {el_diff:>8} ({el_diff/total*100:.2f}%)")
    if el_samples:
        out("  Sample mismatches:")
        for jid, raw, s, d in el_samples:
            out(f"    {jid}: sacct={raw} ({s:.1f}s)  db={d:.1f}s")
    out()

    # -----------------------------------------------------------------------
    # Part 2: TotalCPU time
    # -----------------------------------------------------------------------
    out("=" * 80)
    out("PART 2: TotalCPU time (seconds)")
    out("=" * 80)
    out()

    cpu_match = cpu_diff = cpu_zero = 0
    cpu_samples = []
    for sacct_row, db_row in job_rows:
        s_val = parse_totalcpu(sacct_row[4])
        d_val = float(db_row['total_cpu_sec']) if db_row['total_cpu_sec'] else 0
        if d_val == 0 and s_val == 0:
            cpu_zero += 1
        elif abs(s_val - d_val) < 2:
            cpu_match += 1
        else:
            cpu_diff += 1
            if len(cpu_samples) < 5:
                cpu_samples.append((sacct_row[0], sacct_row[4], s_val, d_val))

    total = cpu_match + cpu_diff + cpu_zero
    out(f"  Match (±1 sec):  {cpu_match:>8} ({cpu_match/total*100:.2f}%)")
    out(f"  Both zero:       {cpu_zero:>8} ({cpu_zero/total*100:.2f}%)")
    out(f"  Differ:          {cpu_diff:>8} ({cpu_diff/total*100:.2f}%)")
    if cpu_samples:
        out("  Sample mismatches:")
        for jid, raw, s, d in cpu_samples:
            out(f"    {jid}: sacct={raw} ({s:.1f}s)  db={d:.1f}s")
    out()

    # -----------------------------------------------------------------------
    # Part 3: AllocCPUs
    # -----------------------------------------------------------------------
    out("=" * 80)
    out("PART 3: AllocCPUs")
    out("=" * 80)
    out()

    ac_match = ac_diff = 0
    ac_samples = []
    for sacct_row, db_row in job_rows:
        s_val = int(sacct_row[6]) if sacct_row[6] else 0
        d_val = int(db_row['alloc_cpus']) if db_row['alloc_cpus'] else 0
        if s_val == d_val:
            ac_match += 1
        else:
            ac_diff += 1
            if len(ac_samples) < 5:
                ac_samples.append((sacct_row[0], s_val, d_val))

    total = ac_match + ac_diff
    out(f"  Match:           {ac_match:>8} ({ac_match/total*100:.2f}%)")
    out(f"  Differ:          {ac_diff:>8} ({ac_diff/total*100:.2f}%)")
    if ac_samples:
        out("  Sample mismatches:")
        for jid, s, d in ac_samples:
            out(f"    {jid}: sacct={s}  db={d}")
    out()

    # -----------------------------------------------------------------------
    # Part 4: ReqMem (total requested memory in bytes)
    # -----------------------------------------------------------------------
    out("=" * 80)
    out("PART 4: ReqMem (total requested memory, bytes)")
    out("=" * 80)
    out()
    out("sacct reports ReqMem as a human-readable string (e.g. '8000M', '24G').")
    out("Our DB pipeline stores reqmem_bytes from tres_req TRES ID 2 (MB) * 1024^2.")
    out()

    rm_exact = rm_diff = rm_zero = 0
    rm_samples_ok = []
    rm_samples_diff = []

    # Per mem_type breakdown
    by_type = {}
    for sacct_row, db_row in job_rows:
        s_val = parse_mem_value(sacct_row[7])
        d_val = float(db_row['reqmem_bytes']) if db_row['reqmem_bytes'] else 0
        mem_type = db_row['mem_type']
        cpus = int(db_row['alloc_cpus']) if db_row['alloc_cpus'] else 1

        if s_val == 0 and d_val == 0:
            rm_zero += 1
            continue

        match = abs(d_val / s_val - 1.0) < 0.001 if s_val > 0 else False
        if match:
            rm_exact += 1
            if len(rm_samples_ok) < 5:
                rm_samples_ok.append((sacct_row[0], sacct_row[7], s_val, d_val,
                                      mem_type, cpus))
        else:
            rm_diff += 1
            if len(rm_samples_diff) < 5:
                ratio = d_val / s_val if s_val > 0 else float('inf')
                rm_samples_diff.append((sacct_row[0], sacct_row[7], s_val, d_val,
                                        mem_type, cpus, ratio))

        key = mem_type
        if key not in by_type:
            by_type[key] = {'match': 0, 'diff': 0}
        by_type[key]['match' if match else 'diff'] += 1

    total = rm_exact + rm_diff + rm_zero
    out(f"  Exact match (±0.1%): {rm_exact:>8} ({rm_exact/total*100:.2f}%)")
    out(f"  Both zero:           {rm_zero:>8} ({rm_zero/total*100:.2f}%)")
    out(f"  Differ:              {rm_diff:>8} ({rm_diff/total*100:.2f}%)")
    out()
    out("  By memory type:")
    for mt, counts in sorted(by_type.items()):
        t = counts['match'] + counts['diff']
        out(f"    {mt:>10}: {counts['match']:>6} match, {counts['diff']:>4} diff "
            f"(of {t})")
    out()
    if rm_samples_ok:
        out("  Sample matches:")
        out(f"    {'JobID':>10} {'sacct_ReqMem':>14} {'sacct_bytes':>16} "
            f"{'db_reqmem_bytes':>16} {'mem_type':>10} {'cpus':>5}")
        for jid, raw, sb, db_b, mt, cpus in rm_samples_ok:
            out(f"    {jid:>10} {raw:>14} {sb:>16.0f} {db_b:>16.0f} {mt:>10} {cpus:>5}")
    if rm_samples_diff:
        out("  Sample mismatches:")
        for jid, raw, sb, db_b, mt, cpus, ratio in rm_samples_diff:
            out(f"    {jid}: sacct={raw} ({sb:.0f})  db={db_b:.0f}  "
                f"ratio={ratio:.4f}  {mt}  cpus={cpus}")
    out()

    # -----------------------------------------------------------------------
    # Part 5: MaxRSS (peak memory usage in bytes)
    # -----------------------------------------------------------------------
    out("=" * 80)
    out("PART 5: MaxRSS (peak memory usage, bytes)")
    out("=" * 80)
    out()
    out("sacct reports MaxRSS at step level; we take the max across steps.")
    out("Our DB pipeline takes max tres_usage_in_max (TRES ID 2) across steps.")
    out()

    mx_exact = mx_close = mx_diff = mx_nomatch = 0
    mx_samples_ok = []
    mx_samples_diff = []

    for sacct_row, db_row in job_rows:
        jid = sacct_row[0]
        db_maxrss = int(db_row['maxrss_bytes']) if (
            db_row['maxrss_bytes'] and db_row['maxrss_bytes'] != 'NULL') else 0

        if jid not in job_sacct_maxrss:
            mx_nomatch += 1
            continue
        s_val = job_sacct_maxrss[jid][0]

        if db_maxrss == 0 or s_val == 0:
            mx_nomatch += 1
            continue

        ratio = db_maxrss / s_val
        if abs(ratio - 1.0) < 0.01:
            mx_exact += 1
            if len(mx_samples_ok) < 5:
                mx_samples_ok.append((jid, job_sacct_maxrss[jid][2], s_val,
                                       db_maxrss))
        elif abs(ratio - 1.0) < 0.05:
            mx_close += 1
        else:
            mx_diff += 1
            if len(mx_samples_diff) < 5:
                mx_samples_diff.append((jid, job_sacct_maxrss[jid][2], s_val,
                                         db_maxrss, ratio))

    total = mx_exact + mx_close + mx_diff
    out(f"  Exact match (±1%):   {mx_exact:>8} ({mx_exact/total*100:.2f}%)")
    out(f"  Close (±5%):         {mx_close:>8} ({mx_close/total*100:.2f}%)")
    out(f"  Differ (>5%):        {mx_diff:>8} ({mx_diff/total*100:.2f}%)")
    out(f"  (No data in one/both: {mx_nomatch})")
    out()
    if mx_samples_ok:
        out("  Sample matches:")
        out(f"    {'JobID':>10} {'sacct_MaxRSS':>14} {'sacct_bytes':>16} {'db_maxrss':>16}")
        for jid, raw, sb, db_b in mx_samples_ok:
            out(f"    {jid:>10} {raw:>14} {sb:>16} {db_b:>16}")
    if mx_samples_diff:
        out("  Sample mismatches (>5%):")
        for jid, raw, sb, db_b, ratio in mx_samples_diff:
            out(f"    {jid}: sacct={raw} ({sb})  db={db_b}  ratio={ratio:.4f}")
    out()

    # -----------------------------------------------------------------------
    # Summary
    # -----------------------------------------------------------------------
    out("=" * 80)
    out("SUMMARY")
    out("=" * 80)
    out()
    out("This script verifies that our MySQL/TRES-based extraction pipeline")
    out("(slurm_utils.py) produces the same job-level metrics as sacct.")
    out()
    out("Key findings:")
    out("  - tres_req TRES ID 2 stores total requested memory in MB")
    out("  - tres_usage_in_max TRES ID 2 stores peak memory usage in bytes")
    out("  - The MB-to-bytes conversion (× 1024²) is correct")
    out("  - Both --mem-per-cpu and --mem (per-node) jobs are handled correctly")
    out("    because tres_req already contains the TOTAL (Slurm pre-multiplies")
    out("    per-cpu values by cpus_req)")
    out(f"  - TotalCPU: {cpu_diff} jobs ({cpu_diff/len(job_rows)*100:.2f}%) where sacct")
    out("    reports 00:00:00 but our DB pipeline found actual CPU time by summing")
    out("    step-level data directly. This suggests sacct's job-level TotalCPU")
    out("    field sometimes fails to aggregate step data, while our pipeline")
    out("    sums it from the step table (create_step_table) and is more complete.")
    out()

print(f"\nOutput saved to {OUTPUT_FILE}", file=sys.stderr)
